[appearance]
prefer_no_csd = true
border_width = 1
corner_radius = 14
border_focused = "#0DB7D4FF"
border_unfocused = "#04404AFF"

[appearance.blur]
enabled = true
passes = 2
noise = 0.03
saturation = 1.0

[overview]
zoom = 0.5
background_tint = "#10101430"
workspace_background = "#00000044"
